\set ON_ERROR_STOP on

do $$ begin
create role gieze_admin;
exception when duplicate_object then raise notice '%, skipping', sqlerrm using errcode = sqlstate;
end $$;

drop schema if exists gieze cascade;
create schema gieze;

set local search_path to gieze, url, pg_catalog, public;

create domain amount as numeric(10, 2) check (value >= 0);
create domain rate as numeric(6, 5) check (value >= 0);

create table client (
  client text not null primary key,
  billing_address text not null,
  shipping_address text default null,
  phone text default null
);

grant all on table client to gieze_admin;

-- create index client_trgm
-- on client
-- using gin (client gin_trgm_ops);

create table product (
  product text not null primary key,
  unit_price_ht amount not null,
  tva_rate rate not null
);

grant all on table product to gieze_admin;

create table bl (
  bl bigint not null primary key generated by default as identity,
  client text not null references client (client) on delete cascade,
  inserted_at timestamptz not null default now(),
  shipped_at date,
  invoiced boolean default false
);

grant all on table bl to gieze_admin;

create table bl_line (
  bl bigint not null references bl (bl) on delete cascade,
  product text not null references product (product) on delete cascade,
  quantity integer not null check (quantity > 0),
  primary key (bl, product)
);

grant all on table bl_line to gieze_admin;

create table invoice (
  invoice text not null primary key,
  increment bigint not null,
  client text not null,
  month date,
  address text not null,
  client_address text not null,
  invoiced_at timestamptz not null,
  deadline_at timestamptz not null,
  total_ht amount not null,
  total_tva amount not null,
  total_ttc amount not null,
  bank_info text not null,
  legal_infos text not null,
  footer text default null,
  unique (client, month, increment)
);

grant all on table invoice to gieze_admin;

create table invoice_line (
  invoice text not null references invoice (invoice)
    on delete cascade
    on update cascade,
  bl text not null,
  product text not null,
  quantity bigint not null check (quantity > 0),
  shipped_at date not null,
  unit_price_ht amount not null,
  total_price_ht amount not null,
  tva_rate rate not null,
  total_tva amount not null,
  total_price_ttc amount not null,
  primary key (invoice, bl, product)
);

grant all on table invoice_line to gieze_admin;

create table admin (
  name text primary key,
  password text not null,
  salt text not null
);

